---
abstract: 'abstract forking with lazy variables'
author:
  - 'and LICENSE'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Fork-Lazy
no_index:
  directory:
    - inc
    - t
recommends:
  Data::Thunk: 0
  Scalar::Lazy: 0
requires:
  Exporter: 0
  IO::Pipe: 0
  Scalar::Defer: 0
  YAML: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
